### PR TITLE
End to end test

### PR DESCRIPTION
**Pull request by kleekich**
@Ben-Mustion Can you do code review for me? Thank you!

### CODE REVIEW

**Review by Ben-Mustion — CHANGES_REQUESTED** [review]
Please update for style formatting by adding a newline at the end of the test.js file

**Comment by kleekich** [comment]
Thank you for you feedback, @Ben-Mustion. Can you clarify what you mean by adding a new line? Thanks.

**Comment by Ben-Mustion** [comment]
The airbnb style guide requires an empty line at the end of each file.

**Comment by kleekich** [comment]
@Ben-Mustion Got it! Thanks, Ben!

**Comment by kleekich** [comment]
Test fails shown above are introduced due to running end to end test(with Puppeteer) on CircleCI. In CircleCi environment, end to end testing with puppeteer requires setting up server and database. In further progress, end to end test will not be performed by CircleCi. test.js file will be modified to have unit test with Enzyme+Jest in a new branch.

**Pull request merged**
